from abc import ABC, abstractmethod

class AuditExecutor(ABC):
    @abstractmethod
    def execute(self, target_address: str, modules: list[str]) -> list[dict]:
        """Return raw results generated by the selected modules."""
