from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class ChainContext:
    web_targets: list[str] = field(default_factory=list)


class AuditExecutor(ABC):
    name: str
    display_name: str
    description: str
    timeout: int

    @abstractmethod
    def execute(
        self,
        target_address: str,
        details: dict | None = None,
        chain_context: ChainContext | None = None,
    ) -> list[dict]:
        """Return raw results generated by the selected modules."""
