from abc import ABC, abstractmethod


class AuditExecutor(ABC):
    name: str
    display_name: str
    description: str
    timeout: int

    @abstractmethod
    def execute(self, target_address: str, details: dict | None = None) -> list[dict]:
        """Return raw results generated by the selected modules."""
